################################################################################################
# File: 20-can0.network
# Author: Andreas
# Date: 20250925
# Purpose: BAN-Bus configuration
#
# Using systemd-networkd (ifupdown with can0 file is not supported in Armbian Ubuntu Boorkworn and newer.) 
# Further options: https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html
#
# Actrivate CAN
#	$ sudo systemctl enable systemd-networkd
#	$ sudo systemctl start systemd-networkd
#	$ sudo udevadm control --reload-rules && sudo udevadm trigger
#	$ sudo reboot
#
# Checking commands - quick
#	$ ip a     					# --> UP & qlen
#	$ networkctl status can0    # --> Config files, driver
#	$ ~/klippy-env/bin/python ~/klipper/klippy/console.py -c can0 e718d4677a2f   	# toolehaead - RP2040
#	$ ~/klippy-env/bin/python ~/klipper/klippy/console.py -c can0 972e3df7498c  	# SKIPR MCU - STM32f407
#
################################################################################################

[Match]
#Name=can0		# Not working
Name=can*

[CAN]
BitRate=1M
# RestartSec=200ms      # not supported on SKIPR due to gs_usb driver.

[Link]
RequiredForOnline=no
